### ISSUE TITLE
Does this work with 8.5?

### ISSUE THREAD

**Issue by SStorm** [grafana/orbit-datasource#2]
This does not load for us using Grafana 8.5.11:
```
Fetch error: 404 Instantiating https://[redacted]/grafana/public/tslib Loading https://[redacted]/grafana/public/plugins/grafana-orbit-datasource/module.js Loading plugins/grafana-orbit-datasource/module
```

I believe there might have been some changes in the [Grafana toolkit](https://community.grafana.com/t/deprecating-grafana-toolkit-versions-from-8-3-0-to-8-3-3/58325), and this plugin might need to be rebuilt?

**Comment by msbt** [comment]
I was just trying to install that as well, same issue on 8.5.6 and 9.1.3

**Comment by msbt** [comment]
@marcusolsson is there anything I can do to help resolving this issue?

**Comment by marcusolsson** [comment]
Hey! Unfortunately I'm no longer with Grafana. The tslib issue also doesn't ring a bell so I'm not sure how helpful I can be here.

**Comment by msbt** [comment]
@marcusolsson ah that's unfortunate indeed, thanks for the heads-up. Any chance you could still release the unreleased 0.1.1 version? I did yarn install/build/dev and it seems to be working (although unsigned), but the go-binaries I didn't manage to compile ;)

**Comment by marcusolsson** [comment]
I don't have access to this repository anymore, so I'd need to rely on someone from the plugins team. And since this plugin is under Grafana Labs (as opposed to my other plugins), I won't be able to submit a release for review.

Maybe @tolzhabayev can help here?

**Comment by briangann** [comment]
i put it into our triage, will followup tomorrow. there was a toolkit version problem that was missing the tslib dependency and required including it in the package.json, but easier to just bump the version of toolkit to latest to ensure it builds correctly.

**Comment by msbt** [comment]
@tolzhabayev thanks for taking a look! Is there any information on if/how/when? Anything I could do to help (i.e. testing)?
